package airport_p3.Presentation.FechaVuelo.Edicion;

import airport_p3.Presentation.FechaVuelo.Edicion.Control_FechaVuelo_Edicion;
import airport_p3.Presentation.FechaVuelo.Edicion.Model_FechaVuelo_Edicion;
import airport_p3.Presentation.Pais.Edicion.*;
import airport_p3.logica.Ciudad;
import airport_p3.logica.Fechavuelo;
import java.util.Observable;
import java.util.Observer;
import javafx.scene.paint.Color;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import airport_p3.logica.Pais;
import airport_p3.logica.Vuelo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Naranjo
 *
 */
public class View_FechaVuelo_Edicion extends javax.swing.JInternalFrame implements Observer {

    public View_FechaVuelo_Edicion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idFechaVuelo = new javax.swing.JTextField();
        FechaVuelo = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        vuelo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        PrecioFechaVuelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DisponiblesFechaVuelo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);
        setTitle("EdicionFechaVuelo");
        setMinimumSize(new java.awt.Dimension(361, 215));

        jLabel1.setText("Id de Fecha Vuelo");

        jLabel2.setText("Vuelo");

        idFechaVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFechaVueloActionPerformed(evt);
            }
        });

        FechaVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaVueloActionPerformed(evt);
            }
        });

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha");

        vuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vueloActionPerformed(evt);
            }
        });

        jLabel4.setText("Disponibles");

        PrecioFechaVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioFechaVueloActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio");

        DisponiblesFechaVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisponiblesFechaVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FechaVuelo)
                            .addComponent(idFechaVuelo)
                            .addComponent(vuelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisponiblesFechaVuelo)
                            .addComponent(PrecioFechaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Eliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agregar)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idFechaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(vuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DisponiblesFechaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PrecioFechaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultar)
                    .addComponent(agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(modificar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        controller.consultar(idFechaVuelo.getText());
    }//GEN-LAST:event_consultarActionPerformed

    private Fechavuelo toFechaVuelo() {
        try{
        Fechavuelo c = new Fechavuelo();
        c.setIdFechaVuelo(idFechaVuelo.getText());
        c.setFecha(this.ParseFecha(FechaVuelo.getText()));
        c.setVuelo((Vuelo)vuelo.getSelectedItem());
        c.setDisponibles(Integer.parseInt(DisponiblesFechaVuelo.getText()));
        c.setPrecio(Double.parseDouble(PrecioFechaVuelo.getText()));
        return c;
        }
        catch(NumberFormatException x){
            this.interruption("Datos Erroneos.");
        }
        return null;
    }
   public void interruption(String msg){
        JOptionPane.showMessageDialog(this, msg);
    }
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        controller.agregar(this.toFechaVuelo());
    }//GEN-LAST:event_agregarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        controller.modificar(this.toFechaVuelo());
    }//GEN-LAST:event_modificarActionPerformed

    private void idFechaVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFechaVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFechaVueloActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        controller.eliminar(this.toFechaVuelo());
    }//GEN-LAST:event_EliminarActionPerformed

    private void FechaVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaVueloActionPerformed

    private void vueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vueloActionPerformed

    private void PrecioFechaVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioFechaVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioFechaVueloActionPerformed

    private void DisponiblesFechaVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisponiblesFechaVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisponiblesFechaVueloActionPerformed
    
    public Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_FechaVuelo_Edicion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DisponiblesFechaVuelo;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField FechaVuelo;
    private javax.swing.JTextField PrecioFechaVuelo;
    private javax.swing.JButton agregar;
    private javax.swing.JButton consultar;
    private javax.swing.ButtonGroup fechas;
    private javax.swing.JTextField idFechaVuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton modificar;
    private javax.swing.JComboBox<Vuelo> vuelo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        renderFechaVuelo(model.getFechaVuelo());
    }

    public void renderFechaVuelo(Fechavuelo c) {
        idFechaVuelo.setText(c.getIdFechaVuelo());
        if(c.getFecha() != null){ FechaVuelo.setText(c.getFechaString()); }
        else{FechaVuelo.setText("year-month-day");}
        this.vuelo.setModel(new DefaultComboBoxModel<Vuelo>(model.getVuelos().toArray(new Vuelo[0])));
        this.vuelo.setSelectedItem(c.getVuelo());
        DisponiblesFechaVuelo.setText(Integer.toString(c.getDisponibles()));
        PrecioFechaVuelo.setText(Double.toString(c.getPrecio()));
    }

    Model_FechaVuelo_Edicion model;
    Control_FechaVuelo_Edicion controller;

    public Model_FechaVuelo_Edicion getModel() {
        return model;
    }

    public void setModel(Model_FechaVuelo_Edicion model) {
        this.model = model;
        model.addObserver(this);
    }

    public Control_FechaVuelo_Edicion getController() {
        return controller;
    }

    public void setController(Control_FechaVuelo_Edicion controller) {
        this.controller = controller;
    }
    
}
