/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airport_p3.Presentation.aplication.Administrador;

import airport_p3.Presentation.aplication.Administrador.Model;
import airport_p3.Presentation.aplication.Administrador.Controller;
import java.awt.Color;
import java.awt.Image;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;

/**
 *
 * @author Escinf
 */
public class View extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.getContentPane().setBackground(Color.GREEN);
        //Image icon = new ImageIcon(getClass().getResource("C:\\Users\\Daniel\\Desktop\\P_III\\Airport_P3\\src/logo2.png")).getImage();
        //this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        panel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        Pais = new javax.swing.JMenu();
        edicionPais = new javax.swing.JMenuItem();
        listadoPais = new javax.swing.JMenuItem();
        edicionCiudad = new javax.swing.JMenu();
        CiudadEdicion = new javax.swing.JMenuItem();
        listadoCiudad = new javax.swing.JMenuItem();
        MenuVuelo = new javax.swing.JMenu();
        EdicionVuelo = new javax.swing.JMenuItem();
        MenuItemListado = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIPE");
        setBackground(new java.awt.Color(0, 255, 0));
        setMinimumSize(new java.awt.Dimension(361, 215));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        Pais.setText("Pais");

        edicionPais.setText("Edicion");
        edicionPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edicionPaisActionPerformed(evt);
            }
        });
        Pais.add(edicionPais);

        listadoPais.setText("Listado");
        listadoPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoPaisActionPerformed(evt);
            }
        });
        Pais.add(listadoPais);

        jMenuBar1.add(Pais);

        edicionCiudad.setText("Ciudad");

        CiudadEdicion.setText("Edicion");
        CiudadEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadEdicionActionPerformed(evt);
            }
        });
        edicionCiudad.add(CiudadEdicion);

        listadoCiudad.setText("Listado");
        listadoCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoCiudadActionPerformed(evt);
            }
        });
        edicionCiudad.add(listadoCiudad);

        jMenuBar1.add(edicionCiudad);

        MenuVuelo.setText("Vuelo");

        EdicionVuelo.setText("Edicion");
        EdicionVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdicionVueloActionPerformed(evt);
            }
        });
        MenuVuelo.add(EdicionVuelo);

        MenuItemListado.setText("Listado");
        MenuItemListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemListadoActionPerformed(evt);
            }
        });
        MenuVuelo.add(MenuItemListado);

        jMenuBar1.add(MenuVuelo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listadoCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoCiudadActionPerformed
        controller.ListadoCiudadShow();
    }//GEN-LAST:event_listadoCiudadActionPerformed

    private void CiudadEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudadEdicionActionPerformed
        controller.EdicionCiudadShow();
    }//GEN-LAST:event_CiudadEdicionActionPerformed

    private void listadoPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoPaisActionPerformed
        controller.ListadoPaisShow();
    }//GEN-LAST:event_listadoPaisActionPerformed

    private void edicionPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edicionPaisActionPerformed
        controller.EdicionPaisShow();
    }//GEN-LAST:event_edicionPaisActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void MenuItemListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemListadoActionPerformed
        controller.ListadoVueloShow();// TODO add your handling code here:
    }//GEN-LAST:event_MenuItemListadoActionPerformed

    private void EdicionVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdicionVueloActionPerformed
       controller.EdicionVueloShow(); // TODO add your handling code here:
    }//GEN-LAST:event_EdicionVueloActionPerformed

    /**
     * @param args the command line arguments
     */
    
      
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CiudadEdicion;
    private javax.swing.JMenuItem EdicionVuelo;
    private javax.swing.JMenuItem MenuItemListado;
    private javax.swing.JMenu MenuVuelo;
    private javax.swing.JMenu Pais;
    private javax.swing.JMenu edicionCiudad;
    private javax.swing.JMenuItem edicionPais;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem listadoCiudad;
    private javax.swing.JMenuItem listadoPais;
    public javax.swing.JDesktopPane panel;
    private javax.swing.ButtonGroup sexo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
    }

    Model model;
    Controller controller;

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
        model.addObserver(this);
    }

    public Controller getController() {
        return controller;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    

}
